#!/bin/bash
run() {
	echo $@
	"$@"
}

status() {
	"$@"
	if [ $? -eq 0 ]; then
		echo "successful"
	else
		echo "failed"
	fi
}

for last; do true; done
case $last in
status) status;;
*) run "$@";;
esac
