#!/bin/bash

TMP=${TMP:-/tmp}

content_like() {
	sudo grep -q $2 $1
	if [[ $? == 0 ]]; then
		echo "yes"
		exit
	else
		echo "no"
		exit 64
	fi
}

content_write() {
	if [ ! -f $1 ]; then
        mkdir -p `dirname $1`
	fi
	echo "writing to $1"
	sudo echo -ne "$CONTENT" > $1
}

status() {
	TMPFILE=$( echo _orc_$1 | tr \/ \\ )
	TMPFILE=$TMP/$TMPFILE
	echo $TMPFILE
	sudo echo -ne "$CONTENT" > $TMPFILE
	diff $1 $TMPFILE > /dev/null
	if [[ $? == 0 ]]; then
		echo set
	else
		echo not_set
	fi
	sudo rm $TMPFILE
}

uri() {
	echo content_$1 | tr \/ \\
}

if [[ $CONTENT == "" ]]; then
	echo enviornment variable CONTENT must be set with sm content 1>&2
	exit 1
fi
case $2 in
status) status $1;;
like) content_like $1 $3;;
uri) uri $1;;
*) content_write $1 $2;;

esac
