#!/bin/bash
#examples
#./line Hello test.txt status
#./line test.txt like Hello
#./line Hello test.txt uri
#./line Hello test.txt existent

source common/functions.sh
TMP=${TMP:-/tmp}

line_add() {
	file=$1

	TMPFILE=$( echo _orc_$file | tr \/ \\ )
    TMPFILE=$TMP/$TMPFILE
    echo $TMPFILE
	if [[ $LINE_NUMBER != "" ]]; then
		sudo sed -i "${LINE_NUMBER} i\\${LINE}" $file
	elif [[ $AFTER_LINE != "" ]]; then
		sudo awk "/$AFTER_LINE/ { print; print \"$LINE\"; next }1" $file > $TMPFILE
		sudo mv $TMPFILE $file
	else
		line_in_file $file $LINE
		if [ $? -eq 0 ]; then
			echo "Line $LINE already exists in file $file"
		else
			echo "Adding line $LINE to the end of file $file"
			sudo echo $LINE >> $file
		fi
	fi
}

line_del() {
	if [[ $LINE_NUMBER != "" ]]; then
		echo "Deleting line of number $LINE_NUMBER from file $1"
		sudo sed -i "${LINE_NUMBER}d" $1
	elif [[ $LINE_PATTERN != "" ]]; then
		echo "Deleting line of pattern $LINE_PATTERN from file $1"
		sudo sed -i -r '/'${LINE_PATTERN}'/d' $1
	fi
}

line_like() {
	sudo grep -q "$LINE_PATTERN" $1
	if [[ $? == 0 ]]; then
		echo "yes"
		exit
	else
		echo "no"
		exit 64
	fi
}

status() {
	line_in_file $1 $LINE
	if [ $? -eq 0 ]; then
		echo "existent"
	else
		echo "non_existent"
	fi
}

uri() {
	echo -n line_$1_ | tr \/ \\
	echo -n $LINE | md5sum | awk '{print $1}'
}

case $2 in
existent) line_add $1;;
non_existent) line_del $1;;
status) status $1;;
uri) uri $1;;
like) line_like $1;;
esac
