#!/bin/bash

run_mysql() {
	echo $SQL
	mysql -u$DB_USERNAME -p$DB_PASSWORD $DATABASE -e "$SQL" 
}

status() {
	echo ""
}

for last; do true; done

case $1 in
status) status;;
mysql) run_mysql ;;
esac
